/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Organization;
import Business.Role.RestaurantManagerRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class RequestLabTestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    EcoSystem system;
    private UserAccount CustomerAccount;
    WorkQueue wq;
    public UserAccount ManagerAccount;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestLabTestJPanel(JPanel userProcessContainer, UserAccount account,EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.CustomerAccount = account;
        this.system = system;
        
        ManagerAccount = searchUser(txtreceiver.getText(), new RestaurantManagerRole());
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        txtreceiver = new javax.swing.JTextField();
        txtdish = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmessage = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setText("Request ");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 130, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Customer :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 120, 30));

        lbl3.setText("Receiver:");
        add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));
        add(txtreceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 89, -1));
        add(txtdish, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 89, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Dish:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jLabel5.setText("Message:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));
        add(txtmessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 89, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        sendorderRequest(ManagerAccount);
        sendorderRequest(CustomerAccount);
        
        txtmessage.setText("");
        txtreceiver.setText("");
        txtdish.setText("");
        
        
        
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed
    
    private void sendorderRequest(UserAccount Account){
        WorkRequest orderRequest = Account.getWorkQueue().addWorkRequest();
        orderRequest.setSender(CustomerAccount);
        orderRequest.setMessage(txtreceiver.getText());
        orderRequest.setDish(txtdish.getText());
        orderRequest.setReceiver(Account);
        orderRequest.setStatus("1");
        
    }
    private UserAccount searchUser(String username, Role role){
        for (UserAccount ua: system.getUserAccountDirectory().getUserAccountList()){
            if (ua.getUsername().equals(username) && ua.getRole().equals(role)){
                return ua;
            }
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl3;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTextField txtdish;
    private javax.swing.JTextField txtmessage;
    private javax.swing.JTextField txtreceiver;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
